version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - mongodb
    command: "npm run debug"